package com.hualala.openapiPlatform.model.dto;

import java.util.ArrayList;
import java.util.List;

public class PredictExample {
    /**
     * Please Ignore This One. This is a template for search information when using the Mybatis
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table predict
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table predict
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table predict
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public PredictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table predict
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCountynameIsNull() {
            addCriterion("countyName is null");
            return (Criteria) this;
        }

        public Criteria andCountynameIsNotNull() {
            addCriterion("countyName is not null");
            return (Criteria) this;
        }

        public Criteria andCountynameEqualTo(String value) {
            addCriterion("countyName =", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotEqualTo(String value) {
            addCriterion("countyName <>", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameGreaterThan(String value) {
            addCriterion("countyName >", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameGreaterThanOrEqualTo(String value) {
            addCriterion("countyName >=", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameLessThan(String value) {
            addCriterion("countyName <", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameLessThanOrEqualTo(String value) {
            addCriterion("countyName <=", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameLike(String value) {
            addCriterion("countyName like", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotLike(String value) {
            addCriterion("countyName not like", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameIn(List<String> values) {
            addCriterion("countyName in", values, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotIn(List<String> values) {
            addCriterion("countyName not in", values, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameBetween(String value1, String value2) {
            addCriterion("countyName between", value1, value2, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotBetween(String value1, String value2) {
            addCriterion("countyName not between", value1, value2, "countyname");
            return (Criteria) this;
        }

        public Criteria andPredictIsNull() {
            addCriterion("predict is null");
            return (Criteria) this;
        }

        public Criteria andPredictIsNotNull() {
            addCriterion("predict is not null");
            return (Criteria) this;
        }

        public Criteria andPredictEqualTo(String value) {
            addCriterion("predict =", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictNotEqualTo(String value) {
            addCriterion("predict <>", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictGreaterThan(String value) {
            addCriterion("predict >", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictGreaterThanOrEqualTo(String value) {
            addCriterion("predict >=", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictLessThan(String value) {
            addCriterion("predict <", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictLessThanOrEqualTo(String value) {
            addCriterion("predict <=", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictLike(String value) {
            addCriterion("predict like", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictNotLike(String value) {
            addCriterion("predict not like", value, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictIn(List<String> values) {
            addCriterion("predict in", values, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictNotIn(List<String> values) {
            addCriterion("predict not in", values, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictBetween(String value1, String value2) {
            addCriterion("predict between", value1, value2, "predict");
            return (Criteria) this;
        }

        public Criteria andPredictNotBetween(String value1, String value2) {
            addCriterion("predict not between", value1, value2, "predict");
            return (Criteria) this;
        }

        public Criteria andTruepovertyIsNull() {
            addCriterion("truePoverty is null");
            return (Criteria) this;
        }

        public Criteria andTruepovertyIsNotNull() {
            addCriterion("truePoverty is not null");
            return (Criteria) this;
        }

        public Criteria andTruepovertyEqualTo(String value) {
            addCriterion("truePoverty =", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyNotEqualTo(String value) {
            addCriterion("truePoverty <>", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyGreaterThan(String value) {
            addCriterion("truePoverty >", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyGreaterThanOrEqualTo(String value) {
            addCriterion("truePoverty >=", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyLessThan(String value) {
            addCriterion("truePoverty <", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyLessThanOrEqualTo(String value) {
            addCriterion("truePoverty <=", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyLike(String value) {
            addCriterion("truePoverty like", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyNotLike(String value) {
            addCriterion("truePoverty not like", value, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyIn(List<String> values) {
            addCriterion("truePoverty in", values, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyNotIn(List<String> values) {
            addCriterion("truePoverty not in", values, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyBetween(String value1, String value2) {
            addCriterion("truePoverty between", value1, value2, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andTruepovertyNotBetween(String value1, String value2) {
            addCriterion("truePoverty not between", value1, value2, "truepoverty");
            return (Criteria) this;
        }

        public Criteria andErrorIsNull() {
            addCriterion("error is null");
            return (Criteria) this;
        }

        public Criteria andErrorIsNotNull() {
            addCriterion("error is not null");
            return (Criteria) this;
        }

        public Criteria andErrorEqualTo(String value) {
            addCriterion("error =", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotEqualTo(String value) {
            addCriterion("error <>", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorGreaterThan(String value) {
            addCriterion("error >", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorGreaterThanOrEqualTo(String value) {
            addCriterion("error >=", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLessThan(String value) {
            addCriterion("error <", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLessThanOrEqualTo(String value) {
            addCriterion("error <=", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLike(String value) {
            addCriterion("error like", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotLike(String value) {
            addCriterion("error not like", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorIn(List<String> values) {
            addCriterion("error in", values, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotIn(List<String> values) {
            addCriterion("error not in", values, "error");
            return (Criteria) this;
        }

        public Criteria andErrorBetween(String value1, String value2) {
            addCriterion("error between", value1, value2, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotBetween(String value1, String value2) {
            addCriterion("error not between", value1, value2, "error");
            return (Criteria) this;
        }

        public Criteria andCountynameLikeInsensitive(String value) {
            addCriterion("upper(countyName) like", value.toUpperCase(), "countyname");
            return (Criteria) this;
        }

        public Criteria andPredictLikeInsensitive(String value) {
            addCriterion("upper(predict) like", value.toUpperCase(), "predict");
            return (Criteria) this;
        }

        public Criteria andTruepovertyLikeInsensitive(String value) {
            addCriterion("upper(truePoverty) like", value.toUpperCase(), "truepoverty");
            return (Criteria) this;
        }

        public Criteria andErrorLikeInsensitive(String value) {
            addCriterion("upper(error) like", value.toUpperCase(), "error");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table predict
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table predict
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}