package com.hualala.openapiPlatform.model.dto;

import java.io.Serializable;

public class Predict implements Serializable {
    /**
     * A class working as an entity of information of prediction.
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.countyName
     *
     * @mbg.generated
     */
    private String countyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.predict
     *
     * @mbg.generated
     */
    private String predict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.truePoverty
     *
     * @mbg.generated
     */
    private String truepoverty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.error
     *
     * @mbg.generated
     */
    private String error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table predict
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.id
     *
     * @return the value of predict.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.id
     *
     * @param id the value for predict.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.countyName
     *
     * @return the value of predict.countyName
     *
     * @mbg.generated
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.countyName
     *
     * @param countyname the value for predict.countyName
     *
     * @mbg.generated
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname == null ? null : countyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.predict
     *
     * @return the value of predict.predict
     *
     * @mbg.generated
     */
    public String getPredict() {
        return predict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.predict
     *
     * @param predict the value for predict.predict
     *
     * @mbg.generated
     */
    public void setPredict(String predict) {
        this.predict = predict == null ? null : predict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.truePoverty
     *
     * @return the value of predict.truePoverty
     *
     * @mbg.generated
     */
    public String getTruepoverty() {
        return truepoverty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.truePoverty
     *
     * @param truepoverty the value for predict.truePoverty
     *
     * @mbg.generated
     */
    public void setTruepoverty(String truepoverty) {
        this.truepoverty = truepoverty == null ? null : truepoverty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.error
     *
     * @return the value of predict.error
     *
     * @mbg.generated
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.error
     *
     * @param error the value for predict.error
     *
     * @mbg.generated
     */
    public void setError(String error) {
        this.error = error == null ? null : error.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", countyname=").append(countyname);
        sb.append(", predict=").append(predict);
        sb.append(", truepoverty=").append(truepoverty);
        sb.append(", error=").append(error);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}