package com.hualala.openapiPlatform.mapper;

import com.hualala.openapiPlatform.model.dto.BfPredict;
import com.hualala.openapiPlatform.model.dto.BfPredictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BfPredictMapper {
    /** There are 2 mappers, this one will use the
     * function of the BfPredictMapper in resources.mapper, where the SQL are,
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    long countByExample(BfPredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int deleteByExample(BfPredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int insert(BfPredict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int insertSelective(BfPredict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    List<BfPredict> selectByExampleWithRowbounds(BfPredictExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    List<BfPredict> selectByExample(BfPredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    BfPredict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BfPredict record, @Param("example") BfPredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BfPredict record, @Param("example") BfPredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BfPredict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BfPredict record);
}