package com.hualala.openapiPlatform.mapper;

import com.hualala.openapiPlatform.model.dto.Predict;
import com.hualala.openapiPlatform.model.dto.PredictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PredictMapper {
    /**
     * There are 2 mappers, this one will use the
     * function of the PredictMapper in resources.mapper, where the SQL are,
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    long countByExample(PredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int deleteByExample(PredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int insert(Predict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int insertSelective(Predict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    List<Predict> selectByExampleWithRowbounds(PredictExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    List<Predict> selectByExample(PredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    Predict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Predict record, @Param("example") PredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Predict record, @Param("example") PredictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Predict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Predict record);
}