package com.hualala.openapiPlatform.model.dto;

import java.util.ArrayList;
import java.util.List;

public class BfPredictExample {
    /**
     *  Please Ignore This One. This is a template for search information when using the Mybatis
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public BfPredictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCountynameIsNull() {
            addCriterion("countyName is null");
            return (Criteria) this;
        }

        public Criteria andCountynameIsNotNull() {
            addCriterion("countyName is not null");
            return (Criteria) this;
        }

        public Criteria andCountynameEqualTo(String value) {
            addCriterion("countyName =", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotEqualTo(String value) {
            addCriterion("countyName <>", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameGreaterThan(String value) {
            addCriterion("countyName >", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameGreaterThanOrEqualTo(String value) {
            addCriterion("countyName >=", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameLessThan(String value) {
            addCriterion("countyName <", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameLessThanOrEqualTo(String value) {
            addCriterion("countyName <=", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameLike(String value) {
            addCriterion("countyName like", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotLike(String value) {
            addCriterion("countyName not like", value, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameIn(List<String> values) {
            addCriterion("countyName in", values, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotIn(List<String> values) {
            addCriterion("countyName not in", values, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameBetween(String value1, String value2) {
            addCriterion("countyName between", value1, value2, "countyname");
            return (Criteria) this;
        }

        public Criteria andCountynameNotBetween(String value1, String value2) {
            addCriterion("countyName not between", value1, value2, "countyname");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateIsNull() {
            addCriterion("foodstampRate is null");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateIsNotNull() {
            addCriterion("foodstampRate is not null");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateEqualTo(String value) {
            addCriterion("foodstampRate =", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateNotEqualTo(String value) {
            addCriterion("foodstampRate <>", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateGreaterThan(String value) {
            addCriterion("foodstampRate >", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateGreaterThanOrEqualTo(String value) {
            addCriterion("foodstampRate >=", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateLessThan(String value) {
            addCriterion("foodstampRate <", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateLessThanOrEqualTo(String value) {
            addCriterion("foodstampRate <=", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateLike(String value) {
            addCriterion("foodstampRate like", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateNotLike(String value) {
            addCriterion("foodstampRate not like", value, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateIn(List<String> values) {
            addCriterion("foodstampRate in", values, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateNotIn(List<String> values) {
            addCriterion("foodstampRate not in", values, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateBetween(String value1, String value2) {
            addCriterion("foodstampRate between", value1, value2, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateNotBetween(String value1, String value2) {
            addCriterion("foodstampRate not between", value1, value2, "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateIsNull() {
            addCriterion("povertyRate is null");
            return (Criteria) this;
        }

        public Criteria andPovertyrateIsNotNull() {
            addCriterion("povertyRate is not null");
            return (Criteria) this;
        }

        public Criteria andPovertyrateEqualTo(String value) {
            addCriterion("povertyRate =", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateNotEqualTo(String value) {
            addCriterion("povertyRate <>", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateGreaterThan(String value) {
            addCriterion("povertyRate >", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateGreaterThanOrEqualTo(String value) {
            addCriterion("povertyRate >=", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateLessThan(String value) {
            addCriterion("povertyRate <", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateLessThanOrEqualTo(String value) {
            addCriterion("povertyRate <=", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateLike(String value) {
            addCriterion("povertyRate like", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateNotLike(String value) {
            addCriterion("povertyRate not like", value, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateIn(List<String> values) {
            addCriterion("povertyRate in", values, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateNotIn(List<String> values) {
            addCriterion("povertyRate not in", values, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateBetween(String value1, String value2) {
            addCriterion("povertyRate between", value1, value2, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateNotBetween(String value1, String value2) {
            addCriterion("povertyRate not between", value1, value2, "povertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateIsNull() {
            addCriterion("malePovertyRate is null");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateIsNotNull() {
            addCriterion("malePovertyRate is not null");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateEqualTo(String value) {
            addCriterion("malePovertyRate =", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateNotEqualTo(String value) {
            addCriterion("malePovertyRate <>", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateGreaterThan(String value) {
            addCriterion("malePovertyRate >", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateGreaterThanOrEqualTo(String value) {
            addCriterion("malePovertyRate >=", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateLessThan(String value) {
            addCriterion("malePovertyRate <", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateLessThanOrEqualTo(String value) {
            addCriterion("malePovertyRate <=", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateLike(String value) {
            addCriterion("malePovertyRate like", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateNotLike(String value) {
            addCriterion("malePovertyRate not like", value, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateIn(List<String> values) {
            addCriterion("malePovertyRate in", values, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateNotIn(List<String> values) {
            addCriterion("malePovertyRate not in", values, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateBetween(String value1, String value2) {
            addCriterion("malePovertyRate between", value1, value2, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateNotBetween(String value1, String value2) {
            addCriterion("malePovertyRate not between", value1, value2, "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateIsNull() {
            addCriterion("femalePovertyRate is null");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateIsNotNull() {
            addCriterion("femalePovertyRate is not null");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateEqualTo(String value) {
            addCriterion("femalePovertyRate =", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateNotEqualTo(String value) {
            addCriterion("femalePovertyRate <>", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateGreaterThan(String value) {
            addCriterion("femalePovertyRate >", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateGreaterThanOrEqualTo(String value) {
            addCriterion("femalePovertyRate >=", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateLessThan(String value) {
            addCriterion("femalePovertyRate <", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateLessThanOrEqualTo(String value) {
            addCriterion("femalePovertyRate <=", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateLike(String value) {
            addCriterion("femalePovertyRate like", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateNotLike(String value) {
            addCriterion("femalePovertyRate not like", value, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateIn(List<String> values) {
            addCriterion("femalePovertyRate in", values, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateNotIn(List<String> values) {
            addCriterion("femalePovertyRate not in", values, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateBetween(String value1, String value2) {
            addCriterion("femalePovertyRate between", value1, value2, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateNotBetween(String value1, String value2) {
            addCriterion("femalePovertyRate not between", value1, value2, "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateIsNull() {
            addCriterion("underhighschoolPovertyRate is null");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateIsNotNull() {
            addCriterion("underhighschoolPovertyRate is not null");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateEqualTo(String value) {
            addCriterion("underhighschoolPovertyRate =", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateNotEqualTo(String value) {
            addCriterion("underhighschoolPovertyRate <>", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateGreaterThan(String value) {
            addCriterion("underhighschoolPovertyRate >", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateGreaterThanOrEqualTo(String value) {
            addCriterion("underhighschoolPovertyRate >=", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateLessThan(String value) {
            addCriterion("underhighschoolPovertyRate <", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateLessThanOrEqualTo(String value) {
            addCriterion("underhighschoolPovertyRate <=", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateLike(String value) {
            addCriterion("underhighschoolPovertyRate like", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateNotLike(String value) {
            addCriterion("underhighschoolPovertyRate not like", value, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateIn(List<String> values) {
            addCriterion("underhighschoolPovertyRate in", values, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateNotIn(List<String> values) {
            addCriterion("underhighschoolPovertyRate not in", values, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateBetween(String value1, String value2) {
            addCriterion("underhighschoolPovertyRate between", value1, value2, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateNotBetween(String value1, String value2) {
            addCriterion("underhighschoolPovertyRate not between", value1, value2, "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateIsNull() {
            addCriterion("highschoolPovertyRate is null");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateIsNotNull() {
            addCriterion("highschoolPovertyRate is not null");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateEqualTo(String value) {
            addCriterion("highschoolPovertyRate =", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateNotEqualTo(String value) {
            addCriterion("highschoolPovertyRate <>", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateGreaterThan(String value) {
            addCriterion("highschoolPovertyRate >", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateGreaterThanOrEqualTo(String value) {
            addCriterion("highschoolPovertyRate >=", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateLessThan(String value) {
            addCriterion("highschoolPovertyRate <", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateLessThanOrEqualTo(String value) {
            addCriterion("highschoolPovertyRate <=", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateLike(String value) {
            addCriterion("highschoolPovertyRate like", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateNotLike(String value) {
            addCriterion("highschoolPovertyRate not like", value, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateIn(List<String> values) {
            addCriterion("highschoolPovertyRate in", values, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateNotIn(List<String> values) {
            addCriterion("highschoolPovertyRate not in", values, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateBetween(String value1, String value2) {
            addCriterion("highschoolPovertyRate between", value1, value2, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateNotBetween(String value1, String value2) {
            addCriterion("highschoolPovertyRate not between", value1, value2, "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateIsNull() {
            addCriterion("collegePovertyRate is null");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateIsNotNull() {
            addCriterion("collegePovertyRate is not null");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateEqualTo(String value) {
            addCriterion("collegePovertyRate =", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateNotEqualTo(String value) {
            addCriterion("collegePovertyRate <>", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateGreaterThan(String value) {
            addCriterion("collegePovertyRate >", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateGreaterThanOrEqualTo(String value) {
            addCriterion("collegePovertyRate >=", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateLessThan(String value) {
            addCriterion("collegePovertyRate <", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateLessThanOrEqualTo(String value) {
            addCriterion("collegePovertyRate <=", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateLike(String value) {
            addCriterion("collegePovertyRate like", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateNotLike(String value) {
            addCriterion("collegePovertyRate not like", value, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateIn(List<String> values) {
            addCriterion("collegePovertyRate in", values, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateNotIn(List<String> values) {
            addCriterion("collegePovertyRate not in", values, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateBetween(String value1, String value2) {
            addCriterion("collegePovertyRate between", value1, value2, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateNotBetween(String value1, String value2) {
            addCriterion("collegePovertyRate not between", value1, value2, "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateIsNull() {
            addCriterion("bachelorPovertyRate is null");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateIsNotNull() {
            addCriterion("bachelorPovertyRate is not null");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateEqualTo(String value) {
            addCriterion("bachelorPovertyRate =", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateNotEqualTo(String value) {
            addCriterion("bachelorPovertyRate <>", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateGreaterThan(String value) {
            addCriterion("bachelorPovertyRate >", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateGreaterThanOrEqualTo(String value) {
            addCriterion("bachelorPovertyRate >=", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateLessThan(String value) {
            addCriterion("bachelorPovertyRate <", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateLessThanOrEqualTo(String value) {
            addCriterion("bachelorPovertyRate <=", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateLike(String value) {
            addCriterion("bachelorPovertyRate like", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateNotLike(String value) {
            addCriterion("bachelorPovertyRate not like", value, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateIn(List<String> values) {
            addCriterion("bachelorPovertyRate in", values, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateNotIn(List<String> values) {
            addCriterion("bachelorPovertyRate not in", values, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateBetween(String value1, String value2) {
            addCriterion("bachelorPovertyRate between", value1, value2, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateNotBetween(String value1, String value2) {
            addCriterion("bachelorPovertyRate not between", value1, value2, "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationIsNull() {
            addCriterion("disabilityCorelation is null");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationIsNotNull() {
            addCriterion("disabilityCorelation is not null");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationEqualTo(String value) {
            addCriterion("disabilityCorelation =", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationNotEqualTo(String value) {
            addCriterion("disabilityCorelation <>", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationGreaterThan(String value) {
            addCriterion("disabilityCorelation >", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationGreaterThanOrEqualTo(String value) {
            addCriterion("disabilityCorelation >=", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationLessThan(String value) {
            addCriterion("disabilityCorelation <", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationLessThanOrEqualTo(String value) {
            addCriterion("disabilityCorelation <=", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationLike(String value) {
            addCriterion("disabilityCorelation like", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationNotLike(String value) {
            addCriterion("disabilityCorelation not like", value, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationIn(List<String> values) {
            addCriterion("disabilityCorelation in", values, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationNotIn(List<String> values) {
            addCriterion("disabilityCorelation not in", values, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationBetween(String value1, String value2) {
            addCriterion("disabilityCorelation between", value1, value2, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationNotBetween(String value1, String value2) {
            addCriterion("disabilityCorelation not between", value1, value2, "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationIsNull() {
            addCriterion("avgHouseAgeCorelation is null");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationIsNotNull() {
            addCriterion("avgHouseAgeCorelation is not null");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationEqualTo(String value) {
            addCriterion("avgHouseAgeCorelation =", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationNotEqualTo(String value) {
            addCriterion("avgHouseAgeCorelation <>", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationGreaterThan(String value) {
            addCriterion("avgHouseAgeCorelation >", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationGreaterThanOrEqualTo(String value) {
            addCriterion("avgHouseAgeCorelation >=", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationLessThan(String value) {
            addCriterion("avgHouseAgeCorelation <", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationLessThanOrEqualTo(String value) {
            addCriterion("avgHouseAgeCorelation <=", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationLike(String value) {
            addCriterion("avgHouseAgeCorelation like", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationNotLike(String value) {
            addCriterion("avgHouseAgeCorelation not like", value, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationIn(List<String> values) {
            addCriterion("avgHouseAgeCorelation in", values, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationNotIn(List<String> values) {
            addCriterion("avgHouseAgeCorelation not in", values, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationBetween(String value1, String value2) {
            addCriterion("avgHouseAgeCorelation between", value1, value2, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationNotBetween(String value1, String value2) {
            addCriterion("avgHouseAgeCorelation not between", value1, value2, "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationIsNull() {
            addCriterion("avgFuelUseageCorelation is null");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationIsNotNull() {
            addCriterion("avgFuelUseageCorelation is not null");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationEqualTo(String value) {
            addCriterion("avgFuelUseageCorelation =", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationNotEqualTo(String value) {
            addCriterion("avgFuelUseageCorelation <>", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationGreaterThan(String value) {
            addCriterion("avgFuelUseageCorelation >", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationGreaterThanOrEqualTo(String value) {
            addCriterion("avgFuelUseageCorelation >=", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationLessThan(String value) {
            addCriterion("avgFuelUseageCorelation <", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationLessThanOrEqualTo(String value) {
            addCriterion("avgFuelUseageCorelation <=", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationLike(String value) {
            addCriterion("avgFuelUseageCorelation like", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationNotLike(String value) {
            addCriterion("avgFuelUseageCorelation not like", value, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationIn(List<String> values) {
            addCriterion("avgFuelUseageCorelation in", values, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationNotIn(List<String> values) {
            addCriterion("avgFuelUseageCorelation not in", values, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationBetween(String value1, String value2) {
            addCriterion("avgFuelUseageCorelation between", value1, value2, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationNotBetween(String value1, String value2) {
            addCriterion("avgFuelUseageCorelation not between", value1, value2, "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationIsNull() {
            addCriterion("fulljobCorelation is null");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationIsNotNull() {
            addCriterion("fulljobCorelation is not null");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationEqualTo(String value) {
            addCriterion("fulljobCorelation =", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationNotEqualTo(String value) {
            addCriterion("fulljobCorelation <>", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationGreaterThan(String value) {
            addCriterion("fulljobCorelation >", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationGreaterThanOrEqualTo(String value) {
            addCriterion("fulljobCorelation >=", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationLessThan(String value) {
            addCriterion("fulljobCorelation <", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationLessThanOrEqualTo(String value) {
            addCriterion("fulljobCorelation <=", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationLike(String value) {
            addCriterion("fulljobCorelation like", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationNotLike(String value) {
            addCriterion("fulljobCorelation not like", value, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationIn(List<String> values) {
            addCriterion("fulljobCorelation in", values, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationNotIn(List<String> values) {
            addCriterion("fulljobCorelation not in", values, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationBetween(String value1, String value2) {
            addCriterion("fulljobCorelation between", value1, value2, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationNotBetween(String value1, String value2) {
            addCriterion("fulljobCorelation not between", value1, value2, "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationIsNull() {
            addCriterion("partjobCorelation is null");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationIsNotNull() {
            addCriterion("partjobCorelation is not null");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationEqualTo(String value) {
            addCriterion("partjobCorelation =", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationNotEqualTo(String value) {
            addCriterion("partjobCorelation <>", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationGreaterThan(String value) {
            addCriterion("partjobCorelation >", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationGreaterThanOrEqualTo(String value) {
            addCriterion("partjobCorelation >=", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationLessThan(String value) {
            addCriterion("partjobCorelation <", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationLessThanOrEqualTo(String value) {
            addCriterion("partjobCorelation <=", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationLike(String value) {
            addCriterion("partjobCorelation like", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationNotLike(String value) {
            addCriterion("partjobCorelation not like", value, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationIn(List<String> values) {
            addCriterion("partjobCorelation in", values, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationNotIn(List<String> values) {
            addCriterion("partjobCorelation not in", values, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationBetween(String value1, String value2) {
            addCriterion("partjobCorelation between", value1, value2, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationNotBetween(String value1, String value2) {
            addCriterion("partjobCorelation not between", value1, value2, "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationIsNull() {
            addCriterion("nojobCorelation is null");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationIsNotNull() {
            addCriterion("nojobCorelation is not null");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationEqualTo(String value) {
            addCriterion("nojobCorelation =", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationNotEqualTo(String value) {
            addCriterion("nojobCorelation <>", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationGreaterThan(String value) {
            addCriterion("nojobCorelation >", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationGreaterThanOrEqualTo(String value) {
            addCriterion("nojobCorelation >=", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationLessThan(String value) {
            addCriterion("nojobCorelation <", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationLessThanOrEqualTo(String value) {
            addCriterion("nojobCorelation <=", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationLike(String value) {
            addCriterion("nojobCorelation like", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationNotLike(String value) {
            addCriterion("nojobCorelation not like", value, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationIn(List<String> values) {
            addCriterion("nojobCorelation in", values, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationNotIn(List<String> values) {
            addCriterion("nojobCorelation not in", values, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationBetween(String value1, String value2) {
            addCriterion("nojobCorelation between", value1, value2, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationNotBetween(String value1, String value2) {
            addCriterion("nojobCorelation not between", value1, value2, "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andPopulationIsNull() {
            addCriterion("population is null");
            return (Criteria) this;
        }

        public Criteria andPopulationIsNotNull() {
            addCriterion("population is not null");
            return (Criteria) this;
        }

        public Criteria andPopulationEqualTo(String value) {
            addCriterion("population =", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationNotEqualTo(String value) {
            addCriterion("population <>", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationGreaterThan(String value) {
            addCriterion("population >", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationGreaterThanOrEqualTo(String value) {
            addCriterion("population >=", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationLessThan(String value) {
            addCriterion("population <", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationLessThanOrEqualTo(String value) {
            addCriterion("population <=", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationLike(String value) {
            addCriterion("population like", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationNotLike(String value) {
            addCriterion("population not like", value, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationIn(List<String> values) {
            addCriterion("population in", values, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationNotIn(List<String> values) {
            addCriterion("population not in", values, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationBetween(String value1, String value2) {
            addCriterion("population between", value1, value2, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationNotBetween(String value1, String value2) {
            addCriterion("population not between", value1, value2, "population");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCountynameLikeInsensitive(String value) {
            addCriterion("upper(countyName) like", value.toUpperCase(), "countyname");
            return (Criteria) this;
        }

        public Criteria andFoodstamprateLikeInsensitive(String value) {
            addCriterion("upper(foodstampRate) like", value.toUpperCase(), "foodstamprate");
            return (Criteria) this;
        }

        public Criteria andPovertyrateLikeInsensitive(String value) {
            addCriterion("upper(povertyRate) like", value.toUpperCase(), "povertyrate");
            return (Criteria) this;
        }

        public Criteria andMalepovertyrateLikeInsensitive(String value) {
            addCriterion("upper(malePovertyRate) like", value.toUpperCase(), "malepovertyrate");
            return (Criteria) this;
        }

        public Criteria andFemalepovertyrateLikeInsensitive(String value) {
            addCriterion("upper(femalePovertyRate) like", value.toUpperCase(), "femalepovertyrate");
            return (Criteria) this;
        }

        public Criteria andUnderhighschoolpovertyrateLikeInsensitive(String value) {
            addCriterion("upper(underhighschoolPovertyRate) like", value.toUpperCase(), "underhighschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andHighschoolpovertyrateLikeInsensitive(String value) {
            addCriterion("upper(highschoolPovertyRate) like", value.toUpperCase(), "highschoolpovertyrate");
            return (Criteria) this;
        }

        public Criteria andCollegepovertyrateLikeInsensitive(String value) {
            addCriterion("upper(collegePovertyRate) like", value.toUpperCase(), "collegepovertyrate");
            return (Criteria) this;
        }

        public Criteria andBachelorpovertyrateLikeInsensitive(String value) {
            addCriterion("upper(bachelorPovertyRate) like", value.toUpperCase(), "bachelorpovertyrate");
            return (Criteria) this;
        }

        public Criteria andDisabilitycorelationLikeInsensitive(String value) {
            addCriterion("upper(disabilityCorelation) like", value.toUpperCase(), "disabilitycorelation");
            return (Criteria) this;
        }

        public Criteria andAvghouseagecorelationLikeInsensitive(String value) {
            addCriterion("upper(avgHouseAgeCorelation) like", value.toUpperCase(), "avghouseagecorelation");
            return (Criteria) this;
        }

        public Criteria andAvgfueluseagecorelationLikeInsensitive(String value) {
            addCriterion("upper(avgFuelUseageCorelation) like", value.toUpperCase(), "avgfueluseagecorelation");
            return (Criteria) this;
        }

        public Criteria andFulljobcorelationLikeInsensitive(String value) {
            addCriterion("upper(fulljobCorelation) like", value.toUpperCase(), "fulljobcorelation");
            return (Criteria) this;
        }

        public Criteria andPartjobcorelationLikeInsensitive(String value) {
            addCriterion("upper(partjobCorelation) like", value.toUpperCase(), "partjobcorelation");
            return (Criteria) this;
        }

        public Criteria andNojobcorelationLikeInsensitive(String value) {
            addCriterion("upper(nojobCorelation) like", value.toUpperCase(), "nojobcorelation");
            return (Criteria) this;
        }

        public Criteria andPopulationLikeInsensitive(String value) {
            addCriterion("upper(population) like", value.toUpperCase(), "population");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bfpredict
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bfpredict
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}